# TeamZones Plugin Konfiguration
#
# Die Welt wird bei X=0 geteilt:
# - Team A: negative X-Koordinaten (X > 0)
# - Team B: positive X-Koordinaten (X < 0)

lobby:
  world: "lobby"
  spawn-point:
    x: 0
    y: 0
    z: 0
    yaw: 0
    pitch: 0

border:
  enabled: true
  render-distance: 32
  particle-type: "REDSTONE" # REDSTONE, FLAME, GLOW, END_ROD
  color: "YELLOW"
  amount: 1
  density:
    horizontal: 2 # (1=dense, 8=parse)
    vertical: 3 # (1=dense, 8=parse)

teams:
  # Team A (Westliche Zone, X > 0)
  team-a:
    display-name: "Team A"
    players:
      - "UUID1"
      - "UUID2"
      - "UUID3"

  # Team B (Östliche Zone, X < 0)
  team-b:
    display-name: "Team B"
    players:
      - "UUID4"
      - "UUID5"
      - "UUID6"

dia-timer:
  yellow: 3000 # 2.5min
  red: 1200 # 1min
  despawn-time: 12000 # default: 6000 ticks = 5min

diamond-limit: 32
diamonds-per-kill: 2

event:
  accept-reward-diamonds: 5

messages:
  prefix: "<dark_gray>[<gold>Server</gold>] </dark_gray>"
  enter-generic-area: "<yellow>Du betrittst jetzt den gegnerischen Bereich!</yellow>"
  no-build-permission: "<red>Du kannst hier nicht bauen oder abbauen!</red>"
  return-to-zone: "<green>Du bist wieder in deiner Zone!</green>"