name: Diawars
version: '2.3-beta'
main: de.davidsw.diawars.Diawars
api-version: '1.21'
author: DavidSW

depend: [NBTAPI]

commands:
  teamzones:
    description: Befehl für die Border
    usage: /<command> <info|border>
    permission: diawars.use
  pvp:
    description: Schaltet PvP an oder aus (5 Minuten Wartezeit)
    usage: /<command> [<status|cancel|toggle>]
    permission: diawars.use
  scores:
    description: Anzeige des Punktestands
    usage: /<command> <info|sidebar>
    permission: diawars.use
  menu:
    description: Hauptmenü des Plugins
    usage: /<command>
    permission: diawars.use
  selfkill:
    description: Self-kill Befehl
    usage: /<command>
    permission: diawars.use
  event:
    description: Event-System des Plugins
    usage: /<command> <create|resume|submit|cancel|join|leave|list|review|accept|reject|reward>
    permission: diawars.use
  lobby:
    description: Betritt oder verlässt die Lobby
    usage: /<command>
    permission: diawars.use
  inv:
    description: Öffnet eine gehaltene Shulker-Box oder Enderkiste
    usage: /<command>
    permission: diawars.use

permissions:
  diawars.use:
    description: Standardberechtigung für gewöhnliche Spieler
    default: true
  diawars.admin:
    description: Erlaubt Admin-Befehle
    default: op
